export const ADD_PRODUCT: string = 'ADD-PRODUCT-IN-BASKET'
export const REMOVE_PRODUCT: string = 'REMOVE-PRODUCT-IN-BASKET'
export const INCREMENT_COUNT_PRODUCT: string =
	'INCREMENT-COUNT-PRODUCT-IN-BASKET'
export const DECREMENT_COUNT_PRODUCT: string =
	'DECREMENT-COUNT-PRODUCT-IN-BASKET'
export const COUNTER_SUM_IN_BASKET: string = 'COUNTER-SUM-IN-BASKET'
export const SET_EMPTY_BASKET: string = 'SET-EMPTY-BASKET'
