export const ADD_PRODUCT = "ADD-PRODUCT-IN-BASKET";
export const REMOVE_PRODUCT = "REMOVE-PRODUCT-IN-BASKET";
export const INCREMENT_COUNT_PRODUCT = "INCREMENT-COUNT-PRODUCT-IN-BASKET";
export const DECREMENT_COUNT_PRODUCT = "DECREMENT-COUNT-PRODUCT-IN-BASKET";
export const COUNTER_SUM_IN_BASKET = "COUNTER-SUM-IN-BASKET";
export const SET_EMPTY_BASKET = "SET-EMPTY-BASKET";
