export const SET_PRODUCTS: string = 'SET-PRODUCTS'
export const DELETE_PRODUCT: string = 'DELETE-PRODUCT'
export const SET_PRODUCT_FOR_EDIT: string = 'SET-PRODUCT-FOR-EDIT'
export const SET_FILTERS_FOR_PRODUCTS: string = 'SET-FILTERS-FOR-PRODUCTS'
export const SET_CATEGORIES_FOR_PRODUCTS: string = 'SET-CATEGORIES-FOR-PRODUCTS'
export const SET_CLASSIFICATIONS_FOR_PRODUCTS: string =
	'SET-CLASSIFICATIONS-FOR-PRODUCTS'
